name: 'G-Mail Support Agent'
description: 'Used to send and process emails from Pull Requests and Commits and forward responses back to GitHub'
inputs:
  command:
    description: 'Command to be executed'
    required: true
    default: ${{ github.event.comment.body }}
  from:
    description: 'Email address of the originator to CC'
    required: true
    default: ''
  github_token:
    description: 'Token to authenticate to the GitHub API'
    required: true
    default: ${{ github.token }}
  template:
    description: 'Format template for the body of the email'
    required: true
    default: ''
  credentials:
    description: 'Minified G-Mail credentials.json content'
    required: true
    default: ''
  token:
    description: 'Minified G-Mail token.json content'
    required: true
    default: ''
runs:
  using: 'docker'
  image: docker://ghcr.io/lindluni/support-gmail:1.0.0
