name: 'G-Mail Support Agent'
description: 'Used to send and process emails from Pull Requests and Commits and forward responses back to GitHub'
inputs:
  command:
    description: 'Command to be executed'
    required: true
    default: ${{ github.event.comment.body }}
  credentials:
    description: 'Minified G-Mail credentials.json content'
    required: true
    default: ''
  from:
    description: 'Email address of the originator to CC'
    required: true
    default: ''
  github_token:
    description: 'Token to authenticate to the GitHub API'
    required: true
    default: ${{ github.token }}
  issue_number:
    description: 'GitHub issue number'
    required: true
    default: ${{ github.event.issue.number }}
  owner:
    description: 'The organization or user who owns the repo'
    required: true
    default: ${{ github.event.organization.login }}
  repository:
    description: 'The repository that triggered the action'
    required: true
    default: ${{ github.event.repository.name }}
  template:
    description: 'Format template for the body of the email'
    required: true
    default: ''
  token:
    description: 'Minified G-Mail token.json content'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
#  image: docker://ghcr.io/lindluni/support-gmail:1.0.0
