name: 'G-Mail Support Agent'
description: 'Used to send and process emails from Pull Requests and Commits and forward responses back to GitHub'
inputs:
  command:
    description: 'Command to be executed'
    required: false
    default: ${{ github.event.comment.body }}
  from:
    description: 'Email address of the originator'
    required: false
    default: ''
  template:
    description: 'Format template for the body of the email'
    required: true
    default: ''
  credentials:
    description: 'Minified G-Mail credentials.json content'
    required: true
    default: ''
  token:
    description: 'Minified G-Mail token.json content'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'