name: Publish
on:
  create:
    tags:
      - v*
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/lindluni/support-gmail:1.0.0